### ISSUE TITLE
TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by HumbleBeck** [crowemi/target-s3#40]
This is related to #1, which is marked as done. However, it is still reproducible in the latest version for schema where fields contain date-time format, for example 
``` 
"created_on": {
      "type": "string",
      "format": "date-time",
      "description": "The date and time when the repository was created."
},
```
    
Here is the error message
```
2024-06-19T14:26:11.471426Z [info     ] joblib.externals.loky.process_executor._RemoteTraceback: cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.471685Z [info     ] """                            cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.471858Z [info     ] Traceback (most recent call last): cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472008Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/_utils.py", line 72, in __call__ cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472176Z [info     ]     return self.func(**kwargs) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472321Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 598, in __call__ cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472472Z [info     ]     return [func(*args, **kwargs) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472615Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 598, in <listcomp> cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472756Z [info     ]     return [func(*args, **kwargs) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.472894Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 509, in _drain_sink cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.473034Z [info     ]     self.drain_one(sink)       cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.473174Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 499, in drain_one cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.473364Z [info     ]     sink.process_batch(draining_status) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.473571Z [info     ]   File "/home/user/dev/target-s3/target_s3/sinks.py", line 65, in process_batch cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.473773Z [info     ]     format_type_client.run()   cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.473972Z [info     ]   File "/home/user/dev/target-s3/target_s3/formats/format_jsonl.py", line 34, in run cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.474112Z [info     ]     return super().run(self.context["records"]) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.474673Z [info     ]   File "/home/user/dev/target-s3/target_s3/formats/format_base.py", line 99, in run cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.474957Z [info     ]     self._write()              cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.475217Z [info     ]   File "/home/user/dev/target-s3/target_s3/formats/format_jsonl.py", line 30, in _write cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.475412Z [info     ]     return super()._write('\n'.join(map(dumps, self.records))) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.475560Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/simplejson/__init__.py", line 378, in dumps cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.475753Z [info     ]     return _default_encoder.encode(obj) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.475968Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/simplejson/encoder.py", line 298, in encode cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.476217Z [info     ]     chunks = self.iterencode(o) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.476462Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/simplejson/encoder.py", line 379, in iterencode cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.476732Z [info     ]     return _iterencode(o, 0)   cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.477085Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/simplejson/encoder.py", line 274, in default cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.477409Z [info     ]     raise TypeError('Object of type %s is not JSON serializable' % cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.477671Z [info     ] TypeError: Object of type datetime is not JSON serializable cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.477929Z [info     ] """                            cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.478151Z [info     ]                                cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.478328Z [info     ] The above exception was the direct cause of the following exception: cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.478556Z [info     ]                                cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.478796Z [info     ] Traceback (most recent call last): cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.479032Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/bin/target-s3", line 8, in <module> cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.479366Z [info     ]     sys.exit(Targets3.cli())   cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.479614Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__ cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.479785Z [info     ]     return self.main(*args, **kwargs) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.480044Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.480220Z [info     ]     rv = self.invoke(ctx)      cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.480373Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.480588Z [info     ]     return ctx.invoke(self.callback, **ctx.params) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.480799Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.483655Z [info     ]     return __callback(*args, **kwargs) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.483901Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 554, in invoke cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.484137Z [info     ]     target.listen(file_input)  cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.484352Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/io_base.py", line 35, in listen cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.484573Z [info     ]     self._process_endofpipe()  cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.484781Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 314, in _process_endofpipe cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.485002Z [info     ]     self.drain_all(is_endofpipe=True) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.485215Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 479, in drain_all cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.485430Z [info     ]     self._drain_all(list(self._sinks_active.values()), self.max_parallelism) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.485631Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/singer_sdk/target_base.py", line 512, in _drain_all cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.485828Z [info     ]     Parallel()(delayed(_drain_sink)(sink=sink) for sink in sink_list) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.486022Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 2007, in __call__ cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.486219Z [info     ]     return output if self.return_generator else list(output) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.486413Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1650, in _get_outputs cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.486607Z [info     ]     yield from self._retrieve() cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.486801Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1754, in _retrieve cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.486995Z [info     ]     self._raise_error_fast()   cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.487190Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.487383Z [info     ]     error_job.get_result(self.timeout) cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.487575Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 745, in get_result cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.487767Z [info     ]     return self._return_or_raise() cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.487965Z [info     ]   File "/home/user/dev/tap-bitbucket/.meltano/loaders/target-s3/venv/lib/python3.10/site-packages/joblib/parallel.py", line 763, in _return_or_raise cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.488857Z [info     ]     raise self._result         cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.489116Z [info     ] TypeError: Object of type datetime is not JSON serializable cmd_type=loader name=target-s3 run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.681247Z [error    ] Loading failed                 code=1 message=TypeError: Object of type datetime is not JSON serializable name=meltano run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3
2024-06-19T14:26:11.682439Z [info     ] ELT could not be completed: Loader failed. cmd_type=elt name=meltano run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.682844Z [info     ] For more detailed log messages re-run the command using 'meltano --log-level=debug ...' CLI flag. cmd_type=elt name=meltano run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.683057Z [info     ] Note that you can also check the generated log file at '/home/user/dev/tap-bitbucket/.meltano/logs/elt/2024-06-19T142543--tap-bitbucket--target-s3/4f8d59d3-b929-4f5c-8b62-3a2d6446f63a/elt.log'. cmd_type=elt name=meltano run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr
2024-06-19T14:26:11.683259Z [info     ] For more information on debugging and logging: https://docs.meltano.com/reference/command-line-interface#debugging cmd_type=elt name=meltano run_id=4f8d59d3-b929-4f5c-8b62-3a2d6446f63a state_id=2024-06-19T142543--tap-bitbucket--target-s3 stdio=stderr

```

Removing format, and keeping it as sting works.

**Comment by emreustundag1618** [comment]
Hi. I am getting this error too. How did you remove format from a property @HumbleBeck ? And did it work?
